# Generated by Django 5.0.4 on 2024-04-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filmstock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_number", models.PositiveIntegerField()),
                ("label", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("year", models.PositiveIntegerField()),
                ("developed", models.DateField(blank=True, null=True)),
                (
                    "filmstock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boxes",
                        to="slides.filmstock",
                    ),
                ),
            ],
        ),
    ]
