# Generated by Django 5.0.4 on 2024-04-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0002_alter_box_options_alter_filmstock_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="label",
            field=models.TextField(blank=True, db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_number", models.PositiveIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="slides.box",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slide",
                "verbose_name_plural": "Slides",
                "ordering": ("slide_number",),
                "unique_together": {("box", "slide_number")},
            },
        ),
    ]
