# Generated by Django 5.0.4 on 2024-04-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0003_alter_box_label_slide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="box",
            name="filmstock",
        ),
        migrations.DeleteModel(
            name="Filmstock",
        ),
    ]
