# Generated by Django 5.0.4 on 2024-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0004_remove_box_filmstock_delete_filmstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="label",
            field=models.TextField(blank=True),
        ),
    ]
