# Generated by Django 5.0.4 on 2024-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0005_alter_box_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="marked",
            field=models.BooleanField(default=False),
        ),
    ]
