# Generated by Django 5.0.4 on 2024-04-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0006_slide_marked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="box",
            options={
                "ordering": ("pk",),
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
            },
        ),
        migrations.CreateModel(
            name="CollectionSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_slides",
                        to="slides.collection",
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_slides",
                        to="slides.slide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Slide",
                "verbose_name_plural": "Collection Slides",
                "ordering": ("ordering",),
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="slides",
            field=models.ManyToManyField(
                through="slides.CollectionSlide", to="slides.slide"
            ),
        ),
    ]
