# Generated by Django 5.0.4 on 2024-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0008_alter_collectionslide_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
