# Generated by Django 5.0.4 on 2024-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0009_collection_collection_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={
                "ordering": ("box_number",),
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ("collection_order",),
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="collectionslide",
            name="slide_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
